# Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# This workflow checks, builds, and tests all artifacts.

name: Build and Check
on:
  pull_request:
    branches:
    - '*'
    types:
    - opened
    - reopened
    - synchronize
    - converted_to_draft
  push:
    branches:
    - main
    - release
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifact Verifier Plugins
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # Install Python to run pre-commit hooks for checking and linting GitHub Actions and other files.
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - name: Check the code
      run: |
        pip install -r dev-requirements.txt
        pre-commit install
        pre-commit run --all-files

    # Install Java.
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: '17'
        distribution: temurin

    # Build and test the artifacts.
    - name: Build the artifacts
      # TODO: Complete the run step.
      run: |
        cd artifact-verifier
        mvn install
        cd ../artifact-verifier-maven
        mvn verify
        cd ../artifact-verifier-gradle
        ./gradlew build
